issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - exportloopref
    - forcetypeassert
    - gofmt
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nilerr
    # - paralleltest # Reference: https://github.com/kunwardeep/paralleltest/issues/14
    - predeclared
    - staticcheck
    - tenv
    - unconvert
    - unparam
    - unused
    - vet
