package tfprotov5

import (
	"context"
)

// GenerateResourceConfigRequest is the request Terraform sends when it wants to generate configuration
// from a resource's state value.
type GenerateResourceConfigRequest struct {
	// TypeName is the name of the resource.
	TypeName string

	// State is the resource's state value.
	State *DynamicValue

	// Experimental, mux would fill this in
	// ResourceSchema *Schema
}

// GenerateResourceConfigResponse is the response from the provider containing the config value
// that can be generated by Terraform.
type GenerateResourceConfigResponse struct {
	// Config contains the resource's config value.
	Config *DynamicValue

	// Diagnostics report errors or warnings related to the creation of the config value.
	Diagnostics []*Diagnostic
}

// GenerateResourceConfigServer is an interface containing the method to generate resource config.
type GenerateResourceConfigServer interface {
	GenerateResourceConfig(context.Context, *GenerateResourceConfigRequest) (*GenerateResourceConfigResponse, error)
}
